name: deployment swissgrid

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      production_target:
        description: 'WÃ¤hle die Produktionsumgebung'
        required: true
        default: 'INT'
        type: choice
        options:
          - INT
          - PROD
      solution_name:
        description: 'Solution Name'
        required: true
        default: GitHubLabSolution
 
env:
  BUILD_ENVIRONMENT_URL: https://org9e7ccea6.crm4.dynamics.com
  INT_ENVIRONMENT_URL: https://orgf617011c.crm4.dynamics.com
  PROD_ENVIRONMENT_URL: https://org0e0972b3.crm4.dynamics.com
  CLIENT_ID_DEV: 0b249eea-86dd-4163-9c07-d47009a5a4f1
  TENANT_ID_DEV: 57cc5cf9-43af-426b-bb89-51f07148ddbe
  CLIENT_ID_INT: 0b249eea-86dd-4163-9c07-d47009a5a4f1
  TENANT_ID_INT: 57cc5cf9-43af-426b-bb89-51f07148ddbe
  CLIENT_ID_PROD: 0b249eea-86dd-4163-9c07-d47009a5a4f1
  TENANT_ID_PROD: 57cc5cf9-43af-426b-bb89-51f07148ddbe
 
jobs:
  convert-to-int_prod:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
    steps:
    - name: Checkout repository
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      with:
        lfs: true
 
    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@6c7b538671a040d11afd8ab94d77bfe3b3ed87e6
 
    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@6c7b538671a040d11afd8ab94d77bfe3b3ed87e6
      with:
        solution-folder: solutions/${{ inputs.solution_name }}
        solution-file: out/solutions/${{ inputs.solution_name }}.zip
        solution-type: Unmanaged
 
    - name: Import solution as unmanaged to build environment
      uses: microsoft/powerplatform-actions/import-solution@6c7b538671a040d11afd8ab94d77bfe3b3ed87e6
      with:
        environment-url: ${{ env.BUILD_ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID_DEV }}
        client-secret: ${{ secrets.PowerPlatformSPN_DEV }}
        tenant-id: ${{ env.TENANT_ID_DEV }}
        solution-file: out/solutions/${{ inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true
 
    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@6c7b538671a040d11afd8ab94d77bfe3b3ed87e6
      with:
        environment-url: ${{ env.BUILD_ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID_DEV }}
        client-secret: ${{ secrets.PowerPlatformSPN_DEV }}
        tenant-id: ${{ env.TENANT_ID_DEV }}
        solution-name: ${{ inputs.solution_name }}
        managed: true
        solution-output-file: out/ship/${{ inputs.solution_name }}_managed.zip
 
    - name: Upload managed solution to GitHub artifact store
      uses: actions/upload-artifact@v4
      with:
        name: managedSolutions
        path: out/ship/
 
  release-to-target:
    needs: [ convert-to-int_prod ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true
 
    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@6c7b538671a040d11afd8ab94d77bfe3b3ed87e6
 
    - name: Download managed solution from GitHub artifact store
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
      with:
        name: managedSolutions
        path: out/release
 
    - name: Import solution to INT environment
      if: ${{ inputs.production_target == 'INT' }}
      uses: microsoft/powerplatform-actions/import-solution@6c7b538671a040d11afd8ab94d77bfe3b3ed87e6
      with:
        environment-url: ${{ env.INT_ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID_INT }}
        client-secret: ${{ secrets.PowerPlatformSPN_INT }}
        tenant-id: ${{ env.TENANT_ID_INT }}
        solution-file: out/release/${{ inputs.solution_name }}_managed.zip
        force-overwrite: true
        publish-changes: true
 
    - name: Import solution to PROD environment
      if: ${{ inputs.production_target == 'PROD' }}
      uses: microsoft/powerplatform-actions/import-solution@6c7b538671a040d11afd8ab94d77bfe3b3ed87e6
      with:
        environment-url: ${{ env.PROD_ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID_PROD }}
        client-secret: ${{ secrets.PowerPlatformSPN_PROD }}
        tenant-id: ${{ env.TENANT_ID_PROD }}
        solution-file: out/release/${{ inputs.solution_name }}_managed.zip
        force-overwrite: true
        publish-changes: true
