name: export-and-branch-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution...'
        required: true
        default: GitHubLabSolution
      # weitere Inputs...

env:
  ENVIRONMENT_URL: 'https://org9e7ccea6.crm4.dynamics.com'
  CLIENT_ID: '0b249eea-86dd-4163-9c07-d47009a5a4f1'
  TENANT_ID: '57cc5cf9-43af-426b-bb89-51f07148ddb'

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate solution version
      id: version
      shell: pwsh
      run: |
        $date = Get-Date -Format "yyyyMMdd"
        $version = "$date.${{ github.run_number }}"
        echo "version=$version" >> $env:GITHUB_OUTPUT

    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: WhoAmI - Verify connection
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}

    - name: Export solution from DEV
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder }}${{ github.event.inputs.solution_name }}.zip

    - name: Unpack solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder }}${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder }}${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Set online solution version
      uses: microsoft/powerplatform-actions/set-online-solution-version@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}
        name: ${{ github.event.inputs.solution_name }}
        version: ${{ steps.version.outputs.version }}

    - name: Branch solution and prepare for PR
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: ${{ github.event.inputs.solution_folder }}${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder }}${{ github.event.inputs.solution_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
